# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/theja/Nextcloud/Desktop/UiUpdater/updater.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(605, 264)
        font = QtGui.QFont()
        font.setFamily("Roboto Slab Light")
        font.setPointSize(10)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(120, 120, 120);\n"
"color: yellow;")
        self.filename = QtWidgets.QLabel(Form)
        self.filename.setGeometry(QtCore.QRect(137, 90, 441, 31))
        self.filename.setStyleSheet("background-color: rgb(80,80,80); border-radius: 7px;\n"
"padding-left: 4px;\n"
"color: white;")
        self.filename.setText("")
        self.filename.setObjectName("filename")
        self.select_file = QtWidgets.QPushButton(Form)
        self.select_file.setGeometry(QtCore.QRect(25, 89, 91, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.select_file.setFont(font)
        self.select_file.setStyleSheet("")
        self.select_file.setObjectName("select_file")
        self.interval = QtWidgets.QSpinBox(Form)
        self.interval.setGeometry(QtCore.QRect(380, 213, 61, 28))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab Medium")
        font.setPointSize(-1)
        self.interval.setFont(font)
        self.interval.setStyleSheet("font-family: \"Roboto Slab Medium\";\n"
"font-size: 12px;\n"
"border: 1px solid white;")
        self.interval.setAlignment(QtCore.Qt.AlignCenter)
        self.interval.setMinimum(1)
        self.interval.setMaximum(20)
        self.interval.setObjectName("interval")
        self.interval_label = QtWidgets.QLabel(Form)
        self.interval_label.setGeometry(QtCore.QRect(365, 184, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.interval_label.setFont(font)
        self.interval_label.setAlignment(QtCore.Qt.AlignCenter)
        self.interval_label.setObjectName("interval_label")
        self.start_timer = QtWidgets.QPushButton(Form)
        self.start_timer.setGeometry(QtCore.QRect(30, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.start_timer.setFont(font)
        self.start_timer.setStyleSheet("QPushButton {\n"
"    border-radius: 6px;\n"
"    border: 1px solid grey;\n"
"    background-color: rgb(70, 70, 70);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-left: 1px solid black;\n"
"    border-bottom: 1px solid black;\n"
"    border-top: 2px solid black;\n"
"    border-right: 2px solid black;\n"
"}")
        self.start_timer.setObjectName("start_timer")
        self.stop_timer = QtWidgets.QPushButton(Form)
        self.stop_timer.setGeometry(QtCore.QRect(130, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.stop_timer.setFont(font)
        self.stop_timer.setStyleSheet("QPushButton {\n"
"    border-radius: 6px;\n"
"    border: 1px solid grey;\n"
"    background-color: rgb(70, 70, 70);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-left: 1px solid black;\n"
"    border-bottom: 1px solid black;\n"
"    border-top: 2px solid black;\n"
"    border-right: 2px solid black;\n"
"}")
        self.stop_timer.setObjectName("stop_timer")
        self.one_time = QtWidgets.QPushButton(Form)
        self.one_time.setGeometry(QtCore.QRect(230, 200, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.one_time.setFont(font)
        self.one_time.setStyleSheet("QPushButton {\n"
"    border-radius: 6px;\n"
"    border: 1px solid grey;\n"
"    background-color: rgb(70, 70, 70);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-left: 1px solid black;\n"
"    border-bottom: 1px solid black;\n"
"    border-top: 2px solid black;\n"
"    border-right: 2px solid black;\n"
"}")
        self.one_time.setObjectName("one_time")
        self.status_label = QtWidgets.QLabel(Form)
        self.status_label.setGeometry(QtCore.QRect(470, 211, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab Medium")
        font.setPointSize(12)
        self.status_label.setFont(font)
        self.status_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_label.setObjectName("status_label")
        self.status = QtWidgets.QLabel(Form)
        self.status.setGeometry(QtCore.QRect(541, 206, 41, 31))
        self.status.setStyleSheet("background-color: rgb(80, 80, 80);\n"
"border-radius: 7px;")
        self.status.setText("")
        self.status.setObjectName("status")
        self.program_title = QtWidgets.QLabel(Form)
        self.program_title.setGeometry(QtCore.QRect(20, 6, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab Light")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.program_title.setFont(font)
        self.program_title.setStyleSheet("color: white;")
        self.program_title.setObjectName("program_title")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(23, 40, 561, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.version_info = QtWidgets.QLabel(Form)
        self.version_info.setGeometry(QtCore.QRect(520, 10, 81, 21))
        self.version_info.setObjectName("version_info")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(463, 189, 3, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(355, 190, 3, 61))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.select_file.setText(_translate("Form", "Select File"))
        self.interval_label.setText(_translate("Form", "Interval"))
        self.start_timer.setText(_translate("Form", "Start"))
        self.stop_timer.setText(_translate("Form", "Stop"))
        self.one_time.setText(_translate("Form", "One-Time"))
        self.status_label.setText(_translate("Form", "Status"))
        self.program_title.setText(_translate("Form", "PyQt5 UI Automated Converter"))
        self.version_info.setText(_translate("Form", "Version 1.4"))
